In [8]:
# in python excecution takes place line by line vertically
# in python execution takes place from right to left horizontally
# in python '=' implies right value is assigning to the left variable yet right variable's value would remain same
# in python '0' is read as null/void. All other numerical value will be acceptable.
# list=[], tuple(), set={}, dict={key:value pair}
# in python (' '/" "/''' ''') have same work i.e. to specify string value. Quotation symbols could be used interchangeably accordingly.
# in dictionary keys should be identical, if not then python will automatically make it irrespective of value.

lst=["this", "that", "is", "am", "are"]
st={"this", "that", "is", "am", "are"}
tpl=("this", "that", "is", "am", "are")
dic={"this":4, "that":4, "is":2, "am":2, "are":2, "this":5}# In key repeated case: that value will be choose where 'and' operation will land it  
print(dic)                                                  # In value repeated case: no effect


#CONDITIONAL OPERATOR
# 'in' operator is only used in list, tuple, set, dictionary

a,b=0,7           #in 
print(a>b)          #>
print(a<b)          #<
print(a!=b)         #!=
print(a<=b)         #<=
print(a>=b)         #>=
print(a==b)         #==
# print(a not b)
# print(5 in a)
print("not a", not a)        #not
print(not b)
print(a or b)       #or-b/w two values,any one value;first cum first service
print(b or a)
print(a and b)      #and-b/w two values, will check both and land on the last value
print(b and a)
print('this' in lst)
print('you' in lst)

{'this': 5, 'that': 4, 'is': 2, 'am': 2, 'are': 2}
False
True
True
True
False
False
not a True
False
7
7
0
0
True
False

In [80]:
#DATA TYPES

#type() function to be use
#all the data types are class in python

print(type(9900000))
print(type(4+4j))
print(type(5/3))
print(type(0+0j))
print("0/6=",0/6)
print("0//6=",0//6)
print(type(0/6))   #for a/b it always give float value while a//b will give integer value
from math import *
print(factorial(4))
# print(type(4!))       #use factorial() function
print(type(4**0))
print(type((23,0.2,2))) 
print(type(0))          
print(type(True))

#CONVERSION

# print(int('hello'))      here string can not be converted as integer(restricted case)
print(type('34'))
#convert 0.5 into complex
print(complex(0.5))
#convert 4**2 into complex
print(complex(4**2))
#convert 4+7j into integer
# print(int(4+7j))         here complex cannot be converteed as integer(restricted case)
# print(int(0+4j))         restricted case
print(set(["this", "that", "is", "am", "are"]))
b='5'
print(b,int(b),float(b))
c='5.3'
print(c,int(float(c)))
e="5"
f=5.3
print(int(e),int(f))
print(float(e),float(f))
a,b,c=0,0.0,'0'
print(bool(a),bool(b),bool(c))
#'0' is a True value whereas 0 is a False value

a=("Q","W","E","R","T","Y","T")
print(list(set(a)))
dic={"he":1000,"she":800,"thirdgender":300}
print(list(dict(dic)))
print(dic)
print(dic.keys())
print(dic.values())
print(dic.items())
print(1000 in dic.values())
print("he" in dic.keys())

<class 'int'>
<class 'complex'>
<class 'float'>
<class 'complex'>
0/6= 0.0
0//6= 0
<class 'float'>
24
<class 'int'>
<class 'tuple'>
<class 'int'>
<class 'bool'>
<class 'str'>
(0.5+0j)
(16+0j)
{'this', 'are', 'am', 'is', 'that'}
5 5 5.0
5.3 5
5 5
5.0 5.3
False False True
['E', 'W', 'Y', 'T', 'R', 'Q']
['he', 'she', 'thirdgender']
{'he': 1000, 'she': 800, 'thirdgender': 300}
dict_keys(['he', 'she', 'thirdgender'])
dict_values([1000, 800, 300])
dict_items([('he', 1000), ('she', 800), ('thirdgender', 300)])
True
True

In [51]:
# Know Boolean Better
# these all are false values, because they are empty
# if " " i.e. space is an character inside string but in programe space is eliminated by pthon automaticaly 
a=0
b=0.0
c=" "
d=[]
e=()
f=set()
g={}
print(bool(a),bool(b),bool(c),bool(d),bool(e),bool(f),bool(g))

False False True False False False False

In [52]:
# ord() & chr() function in ASCII(American standard code for information interchange)

print(ord('A'))
print(chr(65))
print(ord(' '))
print(chr(32))

# ord() gives ASCII value form character
# chr() convert ASCII value to character
print(not [])
print(not (set()))

65
A
32

True
True

In [65]:
# Fun With String ' ',''' '''," "
sta='my Name Is Khan'
a=0
print(a)
a
print(sta)
st2="It's my pleasure"
print(st2)
st3='''He said-"you give me blood, I'll give you freedom"'''
print(st3)

0
my Name Is Khan
It's my pleasure
He said-"you give me blood, I'll give you freedom"

In [81]:
#zip() function in dictionary
#zip() used to merge two list as dictionary/tuple/set/list
a=[54,55,56,' ']
b=[87,85,' ',23]
print(a,b)
print(zip(a,b))
print(dict(zip(a,b)))
print(tuple(zip(a,b)))
print(set(zip(a,b)))
print(list(zip(a,b)))

[54, 55, 56, ' '] [87, 85, ' ', 23]
<zip object at 0x000002B8B64C7040>
{54: 87, 55: 85, 56: ' ', ' ': 23}
((54, 87), (55, 85), (56, ' '), (' ', 23))
{(55, 85), (56, ' '), (54, 87), (' ', 23)}
[(54, 87), (55, 85), (56, ' '), (' ', 23)]

In [124]:
# ADDRESS FINDING USING A FUNCTION id()
# mutables & immutables data type
# mutables: 
# immutables: if same value assign to multiple variables,still the address remain same. eg. int(),str(),
# a variable can take so many values.
# space or block occupy is of value not of variable. if a=7 & b=7 then the adress will be same, if a=7 a=5 then both adress will be diffreent. therefore what matter is value

a=5
a=7 
b=7 
a=0
a=""
a=" "
print(id(a),id(b))
a="hello"
a="hii"
b="hii"
print(id(a),id(b))
a=0+0j
print(id(a))
a=1+9j
b=1+9j

                              #********
print(id(a),id(b))

140703342561480 140703342519272
2992357112944 2992357112944
2992356109840
2992356107472 2992356101264

In [155]:
# OPERATORS
# used pop() in list; range is upto n-2
lst=[1,2,3,4,3]
lst.pop(-1)  
lst.pop(-2)
lst.pop(-3)
print(lst)

from math import *
print(1/4)
print(1//4)
print(1%4)
b=0+9j
c=3+8j
print(b+c)
print(b-c)
d="vanshita"
e="arya"
print(d+e)       #*
# e="vansh"
print(b*c)
print(b**c)

#for factorial use factorial() function
print(factorial(3))

#using functions like floor(),ceil(), abs()
print(floor(1.7)) #gives lower integer value
print(ceil(1.75)) #give greatest integer value
print(abs(-34))   #give modulus value

[2, 4]
0.25
0
1
(3+17j)
(-3+1j)
vanshitaarya
(-72+27j)
(-0.002429448109628638-0.000748953764812645j)
6
1
2
34

In [184]:
# IMPORTANCE OF =
# why lst's address kept changing? *******
a=5
print(id(a))
a=7
print(id(a))
lst=[1,2,3]
print(id(lst))
lst=[1,2,3,4]
print(id(lst))
# =>'=' changes the adress

print('---')
a=[1,2,3]
print(a)
print(id(a))
a.append(4)
print(a)
print(id(a)) #here we can see that no equal is assign just append() function used for modulation; addresss remain same for [1,2,3] & appended [1,2,3,4]
print('----')
a=[1,2,3,4]  #here as we used '=' it automatically changed the address
print(id(a))

140703342519208
140703342519272
2992356371776
2992354956224
---
[1, 2, 3]
2992349052672
[1, 2, 3, 4]
2992349052672
----
2992355129152

In [216]:
# ASSIGNMENT
a,b,c=1,2,3
a=b+1 #3,2,3
b=c+1 #3,4,3
c=a+b #3,4,7
a=a+b+c #14,4,7
b=c-a #14,-7,7
c=a-b-c #14,-7,14
print(a,b,c)
# we noticed that in each and every step as '=' process value kept changing
print(abs(a),abs(b),abs(c))
print('---')
a=7+((4*3)//2)
print(a)
print('---')

# SWAPPING OF TWO DIGIT(using third variable)
a,b=3,4
print(a,b)
c=a
a=b
b=c
print(a,b)
print('---')

#SWAPPING OF TWO DIGIT(without using third variable)
a,b=5,7
print(a,b)
a=a+b #12,7
b=a-b #12-7=5=>12,5
a=a-b #7,5
print(a,b)
print('---')

lst=[1,2,3]
bst=lst
print(lst,bst)
print(id(lst),id(bst)) #here again we seen that the importance of '=';
lst=[3,4,5]
print(lst,bst)
print(id(lst),id(bst)) #'=' changes the address either if is is mutables or immutable
lst.append(6)
bst.append(4)
print(lst,bst)
print(id(lst),id(bst)) #'=' if doesnot used, address will remain unchanged
print('---')
a,b,c=5,6,7
d=a+b+c
print(d)
lst=[1,2,3,4,6]
sm=lst[0]+lst[1]+lst[2]+lst[3]+lst[4]
print(sm)

#sum the given list
#here for longer list we will use 'for' statement; in which take either _ or t which will contain one by one each value in the list 
'''i.e. t=1(first time),
t=2(2nd time)
t=3(3rd time)
.
.
.
t=43(23rd time)'''

#firstly taken value of sum=0
lst=[1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,38,39,41,43]
sm=0
for t in lst:
    sm=sm+t
print(sm)
print('---')
a=0
for t in lst:
    a=t
# a=sm
    # print(a)
print(a)
print('---')

14 -7 14
14 7 14
---
13
---
3 4
4 3
---
5 7
7 5
---
[1, 2, 3] [1, 2, 3]
2992355992384 2992355992384
[3, 4, 5] [1, 2, 3]
2992358346624 2992355992384
[3, 4, 5, 6] [1, 2, 3, 4]
2992358346624 2992355992384
---
18
16
522
---
43
---

In [217]:
# SOME IMPORTANT LIBRARY FUNCTIONS USED IN PYTHON FOR PERFORMING DATA SCIENCE TASK
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# from math import *
# import math
# import math as m

In [ ]:
# RANGE(START,END,JUMP)
'''lst=[0,1,2,...,n]
START=0(bydefault)
  END=(n+1)
JUMP=1(bydefault)
if lst=[1,2,3,4,...,1000]
range(1,1001,1)/range(1001)
if bst=[1,2,...,10]
range(1,11,1)/range(11)
if cst=[2,4,6,8,10]
range(2,11,2)'''

print(set(range(10)))
print(tuple(range(5)))
print(list(range(10)))
print('---')

# ques? Find the sum of numbers from 1 to 50.
sm=0
for t in list(range(1,51)):
    sm=sm+t
print(sm)

#ques? print hello 10 times
a="hello"
for _ in range(1,11):    #why default it printed 5 times hello if range is not determined
    print(a)
print('---')

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
(0, 1, 2, 3, 4)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
---
1275
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello

In [ ]:
#ques? TAKE A INPUT FROM USER IN A VARIABLE NAME n AND PRINT hello n TIMES
n=input()
for _ in range(n):
    print("hello")